config/routes.rb
Rails.application.routes.draw do
  
  
  
  
  resources :importats
  resources :element_predefinits
  resources :operacions
  resources :sistemes
  get 'edificis/llistat_edificis', to: 'edificis#llistat_edificis', :as => :llistat_edificis
  get 'edificis/:id/amagar', to: 'edificis#amagar', :as => :amagar
  get 'edificis/:id/duplicate', to: 'edificis#duplicate', :as => :duplicate
  get 'edificis/:edifici_id/agents', to: 'agents#index', :as => :agents
  get 'edificis/:edifici_id/dades', to: 'dades#index', :as => :dades
  get 'edificis/:edifici_id/documents', to: 'documents#index', :as => :documents
  get 'edificis/:edifici_id/documents/llibre_nou_pdf', to: 'documents#llibre_nou_pdf', :as => :llibre_nou_pdf
  get 'edificis/:edifici_id/documents/manual_habitatge_pdf', to: 'documents#manual_habitatge_pdf', :as => :manual_habitatge_pdf
  get 'edificis/:edifici_id/documents/llibre_existent_pdf', to: 'documents#llibre_existent_pdf', :as => :llibre_existent_pdf
  get 'edificis/:edifici_id/documents/nou(.:format)', to: 'documents#nou', :as => :nou
  get 'edificis/:edifici_id/documents/llibre_nou(.:format)', to: 'documents#llibre_nou', :as => :llibre_nou
  get 'edificis/:edifici_id/documents/calendari_manteniment(.:format)', to: 'documents#calendari_manteniment', :as => :calendari_manteniment
  get 'edificis/:edifici_id/documents/manual_habitatge(.:format)', to: 'documents#manual_habitatge', :as => :manual_habitatge
  get 'edificis/:edifici_id/documents/llibre_existent(.:format)', to: 'documents#llibre_existent', :as => :llibre_existent
  get 'edificis/:edifici_id/documents/vista_pdf_edifici_nou', to: 'documents#vista_pdf_edifici_nou', :as => :vista_pdf_edifici_nou
  get 'edificis/:edifici_id/documents/vista_pdf_edifici_nou_es', to: 'documents#vista_pdf_edifici_nou_es', :as => :vista_pdf_edifici_nou_es
  get 'edificis/:edifici_id/documents/vista_pdf_manual_habitatge', to: 'documents#vista_pdf_manual_habitatge', :as => :vista_pdf_manual_habitatge
  get 'edificis/:edifici_id/documents/vista_pdf_manual_habitatge_es', to: 'documents#vista_pdf_manual_habitatge_es', :as => :vista_pdf_manual_habitatge_es
  get 'edificis/:edifici_id/documents/vista_pdf_edifici_existent', to: 'documents#vista_pdf_edifici_existent', :as => :vista_pdf_edifici_existent
  get 'edificis/:edifici_id/documents/vista_pdf_edifici_existent_es', to: 'documents#vista_pdf_edifici_existent_es', :as => :vista_pdf_edifici_existent_es
  get 'edificis/:edifici_id/documents/vista_pdf_header', to: 'documents#vista_pdf_header', :as => :vista_pdf_header
  get 'edificis/:edifici_id/documents/vista_pdf_footer', to: 'documents#vista_pdf_footer', :as => :vista_pdf_footer

  get 'edificis/:edifici_id/documents/exporta_xml', to: 'documents#exporta_xml', :as => :exporta_xml

  get 'edificis/:edifici_id/sistemes/afegir_sistema', to: 'sistemes#afegir_sistema', :as => :afegir_sistema
  get 'edificis/:edifici_id/referencies/crear_llistat', to: 'referencies#crear_llistat', :as => :crear_llistat
  get 'edificis/:edifici_id/referencies/calendari', to: 'referencies#calendari', :as => :calendari

  get 'edificis/:edifici_id/pagaments/validar_dades', to: 'pagaments#validar_dades', :as => :validar_dades 
  get 'pagaments/update_pagament', to: 'pagaments#update_pagament', :as => :update_pagament
  get 'edificis/:edifici_id/crear_pagament', to: 'pagaments#crear_pagament', :as => :crear_pagament 
  get 'edificis/:edifici_id/pagaments/error_factura', to: 'pagaments#error_factura', :as => :error_factura 
  get 'edificis/:edifici_id/pagaments/error_pagament', to: 'pagaments#error_pagament', :as => :error_pagament 
  get 'edificis/:edifici_id/usuari_factures/mostra_dades', to: 'usuari_factures#mostra_dades', :as => :mostra_dades
  
  resources :edificis do
    resources :identificacions
    resources :promotors
    resources :projectistes
    resources :constructors
    resources :directors
    resources :execucio_directors
    resources :laboratoris
    resources :sistemes
    resources :referencies
    resources :entitat_controls
    resources :subministradors
    resources :industrials
    resources :fonamentacions
    resources :estructures
    resources :tancaments_verticals
    resources :cobertes
    resources :particions
    resources :sanejaments
    resources :aigues
    resources :climatitzacions
    resources :electricitats
    resources :gas
    resources :ventilacions
    resources :incendis
    resources :ascensors
    resources :especials
    resources :telecomunicacions
    resources :elements
    resources :checklist_nou_plurifamiliars
    resources :checklist_nou_unifamiliars
    resources :checklist_existent_plurifamiliars
    resources :checklist_nou_terciaris
    resources :entitats
    resources :carregues
    resources :regim_especials
    resources :regim_propietats
    resources :declaracions
    resources :llicencies
    resources :garantia_instalacions
    resources :garantia_promotors
    resources :coordinadors
    resources :colaboradors
    resources :garantia_constructors
    resources :energia_certificats
    resources :referencia_calendaris
    resources :aptitud_certificats
    resources :iites
    resources :info_usuaris
    resources :pagaments
    resources :empresa_factures
    resources :usuari_factures
    resources :signatura_llibres
    resources :signatura_instruccions
    resources :signatura_promotors
    resources :inscripcio_registrals
  end
  
  
  devise_for :users
  
  
  get 'pagaments/llistat_pagaments'
  get 'pagaments/detall_pagament'
  get 'pagaments/cambra_projects'
  
  
  
  
  get 'home/index'
  get 'home/tutorial'
  get 'home/permisos'
  get 'home/contacta'
  get 'home/avis'
  root :to => "home#index"
  
  match ':controller(/:action(/:id))', :via => [:get, :post]
  

end

app/models/ga.rb
class Ga < ActiveRecord::Base

	belongs_to :edifici

end

app/controllers/gas_controller.rb
class GasController < ApplicationController
  include CheckUser
  include SetSistemes
  before_action :set_sistemes, only: [:show, :edit, :update, :destroy]
  layout 'edifici'

  # GET /gas
  # GET /gas.json
  def index
    @gas = Ga.all
  end

  # GET /gas/1
  # GET /gas/1.json
  def show
  end

  # GET /gas/new
  def new
    @ga = Ga.new
  end

  # GET /gas/1/edit
  def edit
    # Comprovació edifici pertany a usuari
    check_user_edifici
    # Comprovació pàgina correspon a edifici
    if @edifici.ga.id != params[:id].to_i
      redirect_to home_permisos_path
    end

    @submenu_actiu = 'sistemes'
    @menu_sistemes_actiu = 'gas'
    @elements = Element.where(:edifici_id => @edifici.id, :sistema_element => 'gas')
  end

  # POST /gas
  # POST /gas.json
  def create
    @ga = Ga.new(ga_params)

    respond_to do |format|
      if @ga.save
        format.html { redirect_to @ga, notice: 'Ga was successfully created.' }
        format.json { render :show, status: :created, location: @ga }
      else
        format.html { render :new }
        format.json { render json: @ga.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gas/1
  # PATCH/PUT /gas/1.json
  def update
    respond_to do |format|
      if @ga.update(ga_params)
        format.html { redirect_to edit_edifici_ga_path, notice: t('.guardat_ok') }
        format.json { render :show, status: :ok, location: @ga }
      else
        format.html { render :edit }
        format.json { render json: @ga.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gas/1
  # DELETE /gas/1.json
  def destroy
    @ga.destroy
    respond_to do |format|
      format.html { redirect_to gas_url, notice: 'Ga was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ga
      @ga = Ga.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ga_params
      params.require(:ga).permit(:edifici_id, :instalacio_gas, :diposit_aire_lliure, :diposit_enterrat)
    end
end

app/helpers/gas_helper.rb
module GasHelper
end

app/views/gas/_form.html.erb
<%= simple_form_for([@edifici, @ga]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :edifici_id, :as => :hidden, :input_html => { :value => @edifici.id } %>
    <div class="row">
      <div class="medium-12 columns">
        <div class="titol-sistema"><%= t('.titol_gas') %></div>
      </div>
    </div>

    <% flash.each do |key, value| %>
      <div class="row">
        <div class="large-6 columns end">
          <div data-alert class="alert-box success radius">
            <%= value %>
            <a href="#" class="close">&times;</a>
          </div>
        </div>
      </div>
    <% end %>

    <div class="row">
      <div class="medium-12 columns">
        <div class="titol-subsistema"><%= t('.caracteristiques_generals') %></div>
        <%= f.input :instalacio_gas %>
        <%= f.input :diposit_aire_lliure %>
    		<%= f.input :diposit_enterrat %>
    	</div>
    </div>
  </div>

  <div class="row">
    <div class="medium-12 columns">
      <div class="form-actions">
        <%= f.button :submit, t('.guardar'), :class => 'button small radius right botodreta' %>
      </div>
    </div>
  </div>
<% end %>

app/views/gas/edit.html.erb
<div id="modal-elements" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
  <h3 id="modalTitle"><%= t('.nou_element') %></h3>
  <div id="formulari-element" class="formulari-element">
  </div>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<div class="background-seccio">
	<div class="row">
		<div class="large-12 columns">
			<div class="titol-seccio">
				<%= t('.titol_sistemes') %>
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="medium-3 columns">
			<%= render 'layouts/menu_sistemes' %>
		</div>
		<div class="medium-9 columns">
			<div class="formulari-sistema">
				<%= render 'form' %>
				<div class="titol-subsistema"><%= t('.altres_elements') %></div>
				
				<div id="elements">
					<%= render  :partial => '/elements/llistat_elements' %>
				</div>
				<div class="row">
					<div class="medium-12 columns">
						<div class="elements-usuari">
							<%= link_to (new_edifici_element_path(:sistema => 'gas')), remote: true do %>
								<div class="afegir-element right"><span class="suma">+</span> <%= t('.afegir_element') %></div>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/gas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gas</h1>

<table>
  <thead>
    <tr>
      <th>Edifici</th>
      <th>Diposit aire lliure</th>
      <th>Diposit enterrat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gas.each do |ga| %>
      <tr>
        <td><%= ga.edifici_id %></td>
        <td><%= ga.diposit_aire_lliure %></td>
        <td><%= ga.diposit_enterrat %></td>
        <td><%= link_to 'Show', ga %></td>
        <td><%= link_to 'Edit', edit_ga_path(ga) %></td>
        <td><%= link_to 'Destroy', ga, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ga', new_ga_path %>

app/views/gas/new.html.erb
<h1>New Ga</h1>

<%= render 'form' %>

<%= link_to 'Back', gas_path %>

app/views/gas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Edifici:</strong>
  <%= @ga.edifici_id %>
</p>

<p>
  <strong>Diposit aire lliure:</strong>
  <%= @ga.diposit_aire_lliure %>
</p>

<p>
  <strong>Diposit enterrat:</strong>
  <%= @ga.diposit_enterrat %>
</p>

<%= link_to 'Edit', edit_ga_path(@ga) %> |
<%= link_to 'Back', gas_path %>