config/routes.rb
Rails.application.routes.draw do
  
  
  
  
  resources :importats
  resources :element_predefinits
  resources :operacions
  resources :sistemes
  get 'edificis/llistat_edificis', to: 'edificis#llistat_edificis', :as => :llistat_edificis
  get 'edificis/:id/amagar', to: 'edificis#amagar', :as => :amagar
  get 'edificis/:id/duplicate', to: 'edificis#duplicate', :as => :duplicate
  get 'edificis/:edifici_id/agents', to: 'agents#index', :as => :agents
  get 'edificis/:edifici_id/dades', to: 'dades#index', :as => :dades
  get 'edificis/:edifici_id/documents', to: 'documents#index', :as => :documents
  get 'edificis/:edifici_id/documents/llibre_nou_pdf', to: 'documents#llibre_nou_pdf', :as => :llibre_nou_pdf
  get 'edificis/:edifici_id/documents/manual_habitatge_pdf', to: 'documents#manual_habitatge_pdf', :as => :manual_habitatge_pdf
  get 'edificis/:edifici_id/documents/llibre_existent_pdf', to: 'documents#llibre_existent_pdf', :as => :llibre_existent_pdf
  get 'edificis/:edifici_id/documents/nou(.:format)', to: 'documents#nou', :as => :nou
  get 'edificis/:edifici_id/documents/llibre_nou(.:format)', to: 'documents#llibre_nou', :as => :llibre_nou
  get 'edificis/:edifici_id/documents/calendari_manteniment(.:format)', to: 'documents#calendari_manteniment', :as => :calendari_manteniment
  get 'edificis/:edifici_id/documents/manual_habitatge(.:format)', to: 'documents#manual_habitatge', :as => :manual_habitatge
  get 'edificis/:edifici_id/documents/llibre_existent(.:format)', to: 'documents#llibre_existent', :as => :llibre_existent
  get 'edificis/:edifici_id/documents/vista_pdf_edifici_nou', to: 'documents#vista_pdf_edifici_nou', :as => :vista_pdf_edifici_nou
  get 'edificis/:edifici_id/documents/vista_pdf_edifici_nou_es', to: 'documents#vista_pdf_edifici_nou_es', :as => :vista_pdf_edifici_nou_es
  get 'edificis/:edifici_id/documents/vista_pdf_manual_habitatge', to: 'documents#vista_pdf_manual_habitatge', :as => :vista_pdf_manual_habitatge
  get 'edificis/:edifici_id/documents/vista_pdf_manual_habitatge_es', to: 'documents#vista_pdf_manual_habitatge_es', :as => :vista_pdf_manual_habitatge_es
  get 'edificis/:edifici_id/documents/vista_pdf_edifici_existent', to: 'documents#vista_pdf_edifici_existent', :as => :vista_pdf_edifici_existent
  get 'edificis/:edifici_id/documents/vista_pdf_edifici_existent_es', to: 'documents#vista_pdf_edifici_existent_es', :as => :vista_pdf_edifici_existent_es
  get 'edificis/:edifici_id/documents/vista_pdf_header', to: 'documents#vista_pdf_header', :as => :vista_pdf_header
  get 'edificis/:edifici_id/documents/vista_pdf_footer', to: 'documents#vista_pdf_footer', :as => :vista_pdf_footer

  get 'edificis/:edifici_id/documents/exporta_xml', to: 'documents#exporta_xml', :as => :exporta_xml

  get 'edificis/:edifici_id/sistemes/afegir_sistema', to: 'sistemes#afegir_sistema', :as => :afegir_sistema
  get 'edificis/:edifici_id/referencies/crear_llistat', to: 'referencies#crear_llistat', :as => :crear_llistat
  get 'edificis/:edifici_id/referencies/calendari', to: 'referencies#calendari', :as => :calendari

  get 'edificis/:edifici_id/pagaments/validar_dades', to: 'pagaments#validar_dades', :as => :validar_dades 
  get 'pagaments/update_pagament', to: 'pagaments#update_pagament', :as => :update_pagament
  get 'edificis/:edifici_id/crear_pagament', to: 'pagaments#crear_pagament', :as => :crear_pagament 
  get 'edificis/:edifici_id/pagaments/error_factura', to: 'pagaments#error_factura', :as => :error_factura 
  get 'edificis/:edifici_id/pagaments/error_pagament', to: 'pagaments#error_pagament', :as => :error_pagament 
  get 'edificis/:edifici_id/usuari_factures/mostra_dades', to: 'usuari_factures#mostra_dades', :as => :mostra_dades
  
  resources :edificis do
    resources :identificacions
    resources :promotors
    resources :projectistes
    resources :constructors
    resources :directors
    resources :execucio_directors
    resources :laboratoris
    resources :sistemes
    resources :referencies
    resources :entitat_controls
    resources :subministradors
    resources :industrials
    resources :fonamentacions
    resources :estructures
    resources :tancaments_verticals
    resources :cobertes
    resources :particions
    resources :sanejaments
    resources :aigues
    resources :climatitzacions
    resources :electricitats
    resources :gas
    resources :ventilacions
    resources :incendis
    resources :ascensors
    resources :especials
    resources :telecomunicacions
    resources :elements
    resources :checklist_nou_plurifamiliars
    resources :checklist_nou_unifamiliars
    resources :checklist_existent_plurifamiliars
    resources :checklist_nou_terciaris
    resources :entitats
    resources :carregues
    resources :regim_especials
    resources :regim_propietats
    resources :declaracions
    resources :llicencies
    resources :garantia_instalacions
    resources :garantia_promotors
    resources :coordinadors
    resources :colaboradors
    resources :garantia_constructors
    resources :energia_certificats
    resources :referencia_calendaris
    resources :aptitud_certificats
    resources :iites
    resources :info_usuaris
    resources :pagaments
    resources :empresa_factures
    resources :usuari_factures
    resources :signatura_llibres
    resources :signatura_instruccions
    resources :signatura_promotors
    resources :inscripcio_registrals
  end
  
  
  devise_for :users
  
  
  get 'pagaments/llistat_pagaments'
  get 'pagaments/detall_pagament'
  get 'pagaments/cambra_projects'
  
  
  
  
  get 'home/index'
  get 'home/tutorial'
  get 'home/permisos'
  get 'home/contacta'
  get 'home/avis'
  root :to => "home#index"
  
  match ':controller(/:action(/:id))', :via => [:get, :post]
  

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_edifici
  include DocxGenerator
  include PdfGenerator
  include PdfGeneratorEs
  layout 'edifici'
  #layout 'pdf', only: [:vista_pdf_edifici_nou, :doc_pdf]

  def index
    @submenu_actiu = 'documents'
  end

  def llibre_nou_pdf
    if params[:locale] == 'ca'
      url_edifici = 'http://llibreedifici.herokuapp.com/edificis/' + @edifici.id.to_s + '/documents/vista_pdf_edifici_nou?locale=ca'
    elsif params[:locale] == 'es'
      url_edifici = 'http://llibreedifici.herokuapp.com/edificis/' + @edifici.id.to_s + '/documents/vista_pdf_edifici_nou_es?locale=es'
    end
    url_header = 'http://llibreedifici.herokuapp.com/edificis/' + @edifici.id.to_s + '/documents/vista_pdf_header?locale=ca'
    url_footer = 'http://llibreedifici.herokuapp.com/edificis/' + @edifici.id.to_s + '/documents/vista_pdf_footer?locale=ca'
    kit = PDFKit.new(url_edifici, :header_html => url_header, :footer_html => url_footer, :header_spacing => 5, :footer_spacing => 5, :margin_top => '1.0in', :margin_bottom => '1.3in')
    file = kit.to_file(Rails.root + 'tmp/' + 'demo.pdf')
    send_file file, filename: "#{@edifici.nom_edifici}.pdf", disposition: 'attachment'
  end

  def manual_habitatge_pdf
    if params[:locale] == 'ca'
      url_edifici = 'http://llibreedifici.herokuapp.com/edificis/' + @edifici.id.to_s + '/documents/vista_pdf_manual_habitatge?locale=ca'
    elsif params[:locale] == 'es'
      url_edifici = 'http://llibreedifici.herokuapp.com/edificis/' + @edifici.id.to_s + '/documents/vista_pdf_manual_habitatge_es?locale=es'
    end
    url_header = 'http://llibreedifici.herokuapp.com/edificis/' + @edifici.id.to_s + '/documents/vista_pdf_header?locale=ca'
    url_footer = 'http://llibreedifici.herokuapp.com/edificis/' + @edifici.id.to_s + '/documents/vista_pdf_footer?locale=ca'
    kit = PDFKit.new(url_edifici, :header_html => url_header, :footer_html => url_footer, :header_spacing => 5, :footer_spacing => 5, :margin_top => '1.0in', :margin_bottom => '1.3in')
    file = kit.to_file(Rails.root + 'tmp/' + 'demo.pdf')
    send_file file, filename: "#{@edifici.nom_edifici}_manual_habitatge.pdf", disposition: 'attachment'
  end

  def llibre_existent_pdf
    if params[:locale] == 'ca'
      url_edifici = 'http://llibreedifici.herokuapp.com/edificis/' + @edifici.id.to_s + '/documents/vista_pdf_edifici_existent?locale=ca'
    elsif params[:locale] == 'es'
      url_edifici = 'http://llibreedifici.herokuapp.com/edificis/' + @edifici.id.to_s + '/documents/vista_pdf_edifici_existent_es?locale=es'
    end
    url_header = 'http://llibreedifici.herokuapp.com/edificis/' + @edifici.id.to_s + '/documents/vista_pdf_header?locale=ca'
    url_footer = 'http://llibreedifici.herokuapp.com/edificis/' + @edifici.id.to_s + '/documents/vista_pdf_footer?locale=ca'
    kit = PDFKit.new(url_edifici, :header_html => url_header, :footer_html => url_footer, :header_spacing => 5, :footer_spacing => 5, :margin_top => '1.0in', :margin_bottom => '1.3in')
    file = kit.to_file(Rails.root + 'tmp/' + 'demo.pdf')
    send_file file, filename: "#{@edifici.nom_edifici}.pdf", disposition: 'attachment'
  end

  def vista_pdf_edifici_nou
    @text_manual_manteniment = text_manteniment_pdf.html_safe
    @titols_arxiu = espdf_arxiu_documents_edifici_nou.html_safe
    render :layout => 'pdf'
  end

  # Castellà
  def vista_pdf_edifici_nou_es
    @text_manual_manteniment = text_manteniment_pdf_es.html_safe
    @titols_arxiu = espdf_arxiu_documents_edifici_nou_es.html_safe
    render :layout => 'pdf'
  end

  def vista_pdf_manual_habitatge
    @text_manual_manteniment = text_manual_habitatge_pdf.html_safe
    render :layout => 'pdf'
  end

  # Castellà
  def vista_pdf_manual_habitatge_es
    @text_manual_manteniment = text_manual_habitatge_pdf_es.html_safe
    render :layout => 'pdf'
  end

  def vista_pdf_edifici_existent
    # Comprovem si hi ha agents
    @agents = hi_ha_agents()
    @text_manual_manteniment = text_manteniment_pdf.html_safe
    @titols_arxiu = espdf_arxiu_documents_edifici_existent.html_safe
    render :layout => 'pdf'
  end

  #Castellà
  def vista_pdf_edifici_existent_es
    # Comprovem si hi ha agents
    @agents = hi_ha_agents()
    @text_manual_manteniment = text_manteniment_pdf_es.html_safe
    @titols_arxiu = espdf_arxiu_documents_edifici_existent_es.html_safe
    render :layout => 'pdf'
  end

  def vista_pdf_header
    render :layout => false
  end

  def vista_pdf_footer
    render :layout => false
  end

  def calendari_manteniment
    respond_to do |format|
      format.docx do
        if params[:locale] == 'ca'
          doc = DocxReplace::Doc.new("#{Rails.root}/lib/docx_templates/calendari.docx", "#{Rails.root}/tmp")
        elsif params[:locale] == 'es'
          doc = DocxReplace::Doc.new("#{Rails.root}/lib/docx_templates/calendari_es.docx", "#{Rails.root}/tmp")
        end
        doc.replace("$calendari$", calendari)
        tmp_file = Tempfile.new('word_tempate', "#{Rails.root}/tmp")
        doc.commit(tmp_file.path)

        send_file tmp_file.path, filename: "calendari_manteniment.docx", disposition: 'attachment'
      end
    end
  end

  def hi_ha_agents
    if @edifici.promotors.count == 0 && @edifici.projectistes.count == 0 && @edifici.colaboradors.count == 0 && @edifici.constructors.count == 0 && @edifici.directors.count == 0 && @edifici.execucio_directors.count == 0 && @edifici.coordinadors.count == 0 && @edifici.laboratoris.count == 0 && @edifici.entitat_controls.count == 0 && @edifici.subministradors.count == 0 && @edifici.industrials.count == 0
      return false
    else
      return true
    end
  end

  def llibre_nou
    respond_to do |format|
      format.docx do
        doc = DocxReplace::Doc.new("#{Rails.root}/lib/docx_templates/nou.docx", "#{Rails.root}/tmp")
        if @edifici.identificacio.bloc_edifici.blank?
          adreca = @edifici.identificacio.tipus_via_edifici.to_s + ' ' + @edifici.identificacio.via_edifici.to_s + ' ' + @edifici.identificacio.numero_edifici.to_s
        else
          adreca = @edifici.identificacio.tipus_via_edifici.to_s + ' ' + @edifici.identificacio.via_edifici.to_s + ' ' + @edifici.identificacio.numero_edifici.to_s + ', bloc ' + @edifici.identificacio.bloc_edifici.to_s
        end
        doc.replace("$adreca$", adreca)
        doc.replace("$adreca_edifici$", adreca)
        doc.replace("$codi_postal$", @edifici.identificacio.cp_edifici)
        doc.replace("$codi_postal_edifici$", @edifici.identificacio.cp_edifici)
        doc.replace("$poblacio$", @edifici.identificacio.poblacio_edifici)
        doc.replace("$poblacio_edifici$", @edifici.identificacio.poblacio_edifici)
        doc.replace("$provincia$", @edifici.identificacio.provincia_edifici)
        doc.replace("$provincia_edifici$", @edifici.identificacio.provincia_edifici)
        doc.replace("$referencia_cadastral$", @edifici.identificacio.ref_cadastral)
        doc.replace("$any_inici_construccio$", @edifici.identificacio.any_inici_construccio)
        doc.replace("$any_fi_construccio$", @edifici.identificacio.any_fi_construccio)
        doc.replace("$observacions$", @edifici.identificacio.observacions)
        doc.replace("$word_agents$", text_agents)
        doc.replace("$word_dades$", text_dades)
        doc.replace("$word_manual_manteniment$", text_manual_manteniment)
        doc.replace("$titols_arxiu_documents$", esword_arxiu_documents_edifici_nou)
        tmp_file = Tempfile.new('word_tempate', "#{Rails.root}/tmp")
        doc.commit(tmp_file.path)

        send_file tmp_file.path, filename: "#{@edifici.nom_edifici}.docx", disposition: 'attachment'
      end
    end
  end

  def manual_habitatge
    respond_to do |format|
      format.docx do
        doc = DocxReplace::Doc.new("#{Rails.root}/lib/docx_templates/manual.docx", "#{Rails.root}/tmp")
        if @edifici.identificacio.bloc_edifici.blank?
          adreca = @edifici.identificacio.tipus_via_edifici.to_s + ' ' + @edifici.identificacio.via_edifici.to_s + ' ' + @edifici.identificacio.numero_edifici.to_s
        else
          adreca = @edifici.identificacio.tipus_via_edifici.to_s + ' ' + @edifici.identificacio.via_edifici.to_s + ' ' + @edifici.identificacio.numero_edifici.to_s + ', bloc ' + @edifici.identificacio.bloc_edifici.to_s
        end
        doc.replace("$adreca$", adreca)
        doc.replace("$adreca_edifici$", adreca)
        doc.replace("$codi_postal$", @edifici.identificacio.cp_edifici)
        doc.replace("$codi_postal_edifici$", @edifici.identificacio.cp_edifici)
        doc.replace("$poblacio$", @edifici.identificacio.poblacio_edifici)
        doc.replace("$poblacio_edifici$", @edifici.identificacio.poblacio_edifici)
        doc.replace("$provincia$", @edifici.identificacio.provincia_edifici)
        doc.replace("$provincia_edifici$", @edifici.identificacio.provincia_edifici)
        doc.replace("$referencia_cadastral$", @edifici.identificacio.ref_cadastral)
        doc.replace("$any_inici_construccio$", @edifici.identificacio.any_inici_construccio)
        doc.replace("$any_fi_construccio$", @edifici.identificacio.any_fi_construccio)
        doc.replace("$word_manual_habitatge$", text_manual_habitatge)
        tmp_file = Tempfile.new('word_tempate', "#{Rails.root}/tmp")
        doc.commit(tmp_file.path)

        send_file tmp_file.path, filename: "manual_habitatge_#{@edifici.nom_edifici}.docx", disposition: 'attachment'
      end
    end
  end

  def llibre_existent
    respond_to do |format|
      format.docx do
        doc = DocxReplace::Doc.new("#{Rails.root}/lib/docx_templates/existents.docx", "#{Rails.root}/tmp")
        if @edifici.identificacio.bloc_edifici.blank?
          adreca = @edifici.identificacio.tipus_via_edifici.to_s + ' ' + @edifici.identificacio.via_edifici.to_s + ' ' + @edifici.identificacio.numero_edifici.to_s
        else

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/index.html.erb
<div class="background-seccio">
	<div class="row">
		<div class="large-12 columns">
			<div class="titol-seccio">
				<%= t('.titol_documents') %>
			</div>

		</div>
	</div>

	<% if @edifici.tipus_edifici == 'nou_plurifamiliar' %>
	<div class="row">
		<div class="medium-12 columns">
			<div class="container-document">
				<div class="row">
					<div class="medium-4 columns">
						<%= image_tag('document_configuracio.png', :alt => t('.configurar_document'), :class => 'imatge-document') %>
						<%= link_to t('.configurar_document'), edit_edifici_checklist_nou_plurifamiliar_path(@edifici.id, @edifici.checklist_nou_plurifamiliar.id), :class=> "button small radius" %>
						<p><%= t('.text_configurar_document') %></p>
						
					</div>
					<div class="medium-4 columns">
						<%= image_tag('document_llibre.png', :alt => t('.generar_llibre'), :class => 'imatge-document') %>
						<% if params[:locale] == 'ca' %>
							<a href="documents/llibre_nou_pdf?locale=ca" class="button small radius"><%= t('.generar_llibre_pdf') %></a>
						<% elsif params[:locale] == 'es' %>
							<a href="documents/llibre_nou_pdf?locale=es" class="button small radius"><%= t('.generar_llibre_pdf') %></a>
						<% end %>
						<p><%= t('.text_generar_llibre') %></p>
						
					</div>
					<div class="medium-4 columns">
						<%= image_tag('document_manual.png', :alt => t('.generar_manual'), :class => 'imatge-document') %>
						<% if params[:locale] == 'ca' %>
							<a href="documents/manual_habitatge_pdf?locale=ca" class="button small radius"><%= t('.generar_manual_pdf') %></a>
						<% elsif params[:locale] == 'es' %>
							<a href="documents/manual_habitatge_pdf?locale=es" class="button small radius"><%= t('.generar_manual_pdf') %></a>
						<% end %>
						<p><%= t('.text_generar_manual') %></p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="medium-12 columns">
			<div class="container-document">
				<div class="row">
					<div class="medium-6 columns">
						<%= image_tag('document_calendari.png', :alt => t('.generar_calendari'), :class => 'imatge-document') %>
						<% if params[:locale] == 'ca' %>
							<a href="documents/calendari_manteniment.docx?locale=ca" class="button small radius"><%= t('.generar_calendari') %></a>
						<% elsif params[:locale] == 'es' %>
							<a href="documents/calendari_manteniment.docx?locale=es" class="button small radius"><%= t('.generar_calendari') %></a>
						<% end %>
						<p><%= t('.text_generar_calendari') %></p>	
						
					</div>
					<div class="medium-6 columns">
						<%= image_tag('document_xml.png', :alt => t('.exportar_operacions'), :class => 'imatge-document') %>
						<%= link_to t('.exportar_operacions'), exporta_xml_path(:edifici_id => @edifici.id, :format => :xml), :class => 'button small radius'  %>
						<p><%= t('.text_generar_xml') %></p>	
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<% end %>

	<% if @edifici.tipus_edifici == 'nou_unifamiliar' %>
	<div class="row">
		<div class="medium-12 columns">
			<div class="container-document">
				<div class="row">
					<div class="medium-6 columns">
						<%= image_tag('document_configuracio.png', :alt => t('.configurar_document'), :class => 'imatge-document') %>
						<br/>
						<%= link_to t('.configurar_document'), edit_edifici_checklist_nou_unifamiliar_path(@edifici.id, @edifici.checklist_nou_unifamiliar.id), :class=> "button small radius" %>
						<p><%= t('.text_configurar_document') %></p>
						
					</div>
					<div class="medium-6 columns end">
						<%= image_tag('document_llibre.png', :alt => t('.generar_llibre'), :class => 'imatge-document') %>
						<br/>
						<% if params[:locale] == 'ca' %>
							<a href="documents/llibre_nou_pdf?locale=ca" class="button small radius"><%= t('.generar_llibre_pdf') %></a>
						<% elsif params[:locale] == 'es' %>
							<a href="documents/llibre_nou_pdf?locale=es" class="button small radius"><%= t('.generar_llibre_pdf') %></a>
						<% end %>
						<p><%= t('.text_generar_llibre') %></p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="medium-12 columns">
			<div class="container-document">
				<div class="row">
					<div class="medium-6 columns">
						<%= image_tag('document_calendari.png', :alt => t('.generar_calendari'), :class => 'imatge-document') %>
						<% if params[:locale] == 'ca' %>
							<a href="documents/calendari_manteniment.docx?locale=ca" class="button small radius"><%= t('.generar_calendari') %></a>
						<% elsif params[:locale] == 'es' %>
							<a href="documents/calendari_manteniment.docx?locale=es" class="button small radius"><%= t('.generar_calendari') %></a>
						<% end %>
						<p><%= t('.text_generar_calendari') %></p>	
					</div>
					<div class="medium-6 columns">
						<%= image_tag('document_xml.png', :alt => t('.exportar_operacions'), :class => 'imatge-document') %>
						<%= link_to t('.exportar_operacions'), exporta_xml_path(:edifici_id => @edifici.id, :format => :xml), :class => 'button small radius'  %>
						<p><%= t('.text_generar_xml') %></p>	
					</div>
				</div>
			</div>
		</div>
	</div>
	<% end %>

	<% if @edifici.tipus_edifici == 'nou_terciari' %>
	<div class="row">
		<div class="medium-12 columns">
			<div class="container-document">
				<div class="row">
					<div class="medium-6 columns">
						<%= image_tag('document_configuracio.png', :alt => t('.configurar_document'), :class => 'imatge-document') %>
						<%= link_to t('.configurar_document'), edit_edifici_checklist_nou_terciari_path(@edifici.id, @edifici.checklist_nou_terciari.id), :class=> "button small radius" %>
						<p><%= t('.text_configurar_document') %></p>
						
					</div>
					<div class="medium-6 columns">
						<%= image_tag('document_llibre.png', :alt => t('.generar_llibre'), :class => 'imatge-document') %>
						<% if params[:locale] == 'ca' %>
							<a href="documents/llibre_nou_pdf?locale=ca" class="button small radius"><%= t('.generar_llibre_pdf') %></a>
						<% elsif params[:locale] == 'es' %>
							<a href="documents/llibre_nou_pdf?locale=es" class="button small radius"><%= t('.generar_llibre_pdf') %></a>
						<% end %>
						<p><%= t('.text_generar_llibre') %></p>
						
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="medium-12 columns">
			<div class="container-document">
				<div class="row">
					<div class="medium-6 columns">
						<%= image_tag('document_calendari.png', :alt => t('.generar_calendari'), :class => 'imatge-document') %>
						<% if params[:locale] == 'ca' %>
							<a href="documents/calendari_manteniment.docx?locale=ca" class="button small radius"><%= t('.generar_calendari') %></a>
						<% elsif params[:locale] == 'es' %>
							<a href="documents/calendari_manteniment.docx?locale=es" class="button small radius"><%= t('.generar_calendari') %></a>
						<% end %>
						<p><%= t('.text_generar_calendari') %></p>	
						
					</div>
					<div class="medium-6 columns">
						<%= image_tag('document_xml.png', :alt => t('.exportar_operacions'), :class => 'imatge-document') %>
						<%= link_to t('.exportar_operacions'), exporta_xml_path(:edifici_id => @edifici.id, :format => :xml), :class => 'button small radius'  %>
						<p><%= t('.text_generar_xml') %></p>	
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<% end %>

	<% if @edifici.tipus_edifici == 'existent_plurifamiliar' || @edifici.tipus_edifici == 'existent_unifamiliar' %>
	<div class="row">
		<div class="medium-12 columns">
			<div class="container-document">
				<div class="row">
					<div class="medium-6 columns">
						<%= image_tag('document_configuracio.png', :alt => t('.configurar_document'), :class => 'imatge-document') %>
						<br/>
						<%= link_to t('.configurar_document'), edit_edifici_checklist_existent_plurifamiliar_path(@edifici.id, @edifici.checklist_existent_plurifamiliar.id), :class=> "button small radius" %>
						<p><%= t('.text_configurar_document') %></p>
						
					</div>
					<div class="medium-6 columns end">
						<%= image_tag('document_llibre.png', :alt => t('.generar_llibre'), :class => 'imatge-document') %>
						<br/>
						<% if params[:locale] == 'ca' %>
							<a href="documents/llibre_existent_pdf?locale=ca" class="button small radius"><%= t('.generar_llibre_pdf') %></a>
						<% elsif params[:locale] == 'es' %>
							<a href="documents/llibre_existent_pdf?locale=es" class="button small radius"><%= t('.generar_llibre_pdf') %></a>
						<% end %>
						<p><%= t('.text_generar_llibre') %></p>
						
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="medium-12 columns">
			<div class="container-document">
				<div class="row">
					<div class="medium-6 columns">
						<%= image_tag('document_calendari.png', :alt => t('.generar_calendari'), :class => 'imatge-document') %>
						<% if params[:locale] == 'ca' %>
							<a href="documents/calendari_manteniment.docx?locale=ca" class="button small radius"><%= t('.generar_calendari') %></a>
						<% elsif params[:locale] == 'es' %>
							<a href="documents/calendari_manteniment.docx?locale=es" class="button small radius"><%= t('.generar_calendari') %></a>
						<% end %>
						<p><%= t('.text_generar_calendari') %></p>	
					</div>
					<div class="medium-6 columns">
						<%= image_tag('document_xml.png', :alt => t('.exportar_operacions'), :class => 'imatge-document') %>
						<%= link_to t('.exportar_operacions'), exporta_xml_path(:edifici_id => @edifici.id, :format => :xml), :class => 'button small radius'  %>
						<p><%= t('.text_generar_xml') %></p>	
					</div>
				</div>
			</div>
		</div>
	</div>
	<% end %>

</div>

app/views/documents/vista_pdf_footer.html.erb
<div class="espai-visat">
	
</div>