config/routes.rb
Rails.application.routes.draw do
  
  
  
  
  resources :importats
  resources :element_predefinits
  resources :operacions
  resources :sistemes
  get 'edificis/llistat_edificis', to: 'edificis#llistat_edificis', :as => :llistat_edificis
  get 'edificis/:id/amagar', to: 'edificis#amagar', :as => :amagar
  get 'edificis/:id/duplicate', to: 'edificis#duplicate', :as => :duplicate
  get 'edificis/:edifici_id/agents', to: 'agents#index', :as => :agents
  get 'edificis/:edifici_id/dades', to: 'dades#index', :as => :dades
  get 'edificis/:edifici_id/documents', to: 'documents#index', :as => :documents
  get 'edificis/:edifici_id/documents/llibre_nou_pdf', to: 'documents#llibre_nou_pdf', :as => :llibre_nou_pdf
  get 'edificis/:edifici_id/documents/manual_habitatge_pdf', to: 'documents#manual_habitatge_pdf', :as => :manual_habitatge_pdf
  get 'edificis/:edifici_id/documents/llibre_existent_pdf', to: 'documents#llibre_existent_pdf', :as => :llibre_existent_pdf
  get 'edificis/:edifici_id/documents/nou(.:format)', to: 'documents#nou', :as => :nou
  get 'edificis/:edifici_id/documents/llibre_nou(.:format)', to: 'documents#llibre_nou', :as => :llibre_nou
  get 'edificis/:edifici_id/documents/calendari_manteniment(.:format)', to: 'documents#calendari_manteniment', :as => :calendari_manteniment
  get 'edificis/:edifici_id/documents/manual_habitatge(.:format)', to: 'documents#manual_habitatge', :as => :manual_habitatge
  get 'edificis/:edifici_id/documents/llibre_existent(.:format)', to: 'documents#llibre_existent', :as => :llibre_existent
  get 'edificis/:edifici_id/documents/vista_pdf_edifici_nou', to: 'documents#vista_pdf_edifici_nou', :as => :vista_pdf_edifici_nou
  get 'edificis/:edifici_id/documents/vista_pdf_edifici_nou_es', to: 'documents#vista_pdf_edifici_nou_es', :as => :vista_pdf_edifici_nou_es
  get 'edificis/:edifici_id/documents/vista_pdf_manual_habitatge', to: 'documents#vista_pdf_manual_habitatge', :as => :vista_pdf_manual_habitatge
  get 'edificis/:edifici_id/documents/vista_pdf_manual_habitatge_es', to: 'documents#vista_pdf_manual_habitatge_es', :as => :vista_pdf_manual_habitatge_es
  get 'edificis/:edifici_id/documents/vista_pdf_edifici_existent', to: 'documents#vista_pdf_edifici_existent', :as => :vista_pdf_edifici_existent
  get 'edificis/:edifici_id/documents/vista_pdf_edifici_existent_es', to: 'documents#vista_pdf_edifici_existent_es', :as => :vista_pdf_edifici_existent_es
  get 'edificis/:edifici_id/documents/vista_pdf_header', to: 'documents#vista_pdf_header', :as => :vista_pdf_header
  get 'edificis/:edifici_id/documents/vista_pdf_footer', to: 'documents#vista_pdf_footer', :as => :vista_pdf_footer

  get 'edificis/:edifici_id/documents/exporta_xml', to: 'documents#exporta_xml', :as => :exporta_xml

  get 'edificis/:edifici_id/sistemes/afegir_sistema', to: 'sistemes#afegir_sistema', :as => :afegir_sistema
  get 'edificis/:edifici_id/referencies/crear_llistat', to: 'referencies#crear_llistat', :as => :crear_llistat
  get 'edificis/:edifici_id/referencies/calendari', to: 'referencies#calendari', :as => :calendari

  get 'edificis/:edifici_id/pagaments/validar_dades', to: 'pagaments#validar_dades', :as => :validar_dades 
  get 'pagaments/update_pagament', to: 'pagaments#update_pagament', :as => :update_pagament
  get 'edificis/:edifici_id/crear_pagament', to: 'pagaments#crear_pagament', :as => :crear_pagament 
  get 'edificis/:edifici_id/pagaments/error_factura', to: 'pagaments#error_factura', :as => :error_factura 
  get 'edificis/:edifici_id/pagaments/error_pagament', to: 'pagaments#error_pagament', :as => :error_pagament 
  get 'edificis/:edifici_id/usuari_factures/mostra_dades', to: 'usuari_factures#mostra_dades', :as => :mostra_dades
  
  resources :edificis do
    resources :identificacions
    resources :promotors
    resources :projectistes
    resources :constructors
    resources :directors
    resources :execucio_directors
    resources :laboratoris
    resources :sistemes
    resources :referencies
    resources :entitat_controls
    resources :subministradors
    resources :industrials
    resources :fonamentacions
    resources :estructures
    resources :tancaments_verticals
    resources :cobertes
    resources :particions
    resources :sanejaments
    resources :aigues
    resources :climatitzacions
    resources :electricitats
    resources :gas
    resources :ventilacions
    resources :incendis
    resources :ascensors
    resources :especials
    resources :telecomunicacions
    resources :elements
    resources :checklist_nou_plurifamiliars
    resources :checklist_nou_unifamiliars
    resources :checklist_existent_plurifamiliars
    resources :checklist_nou_terciaris
    resources :entitats
    resources :carregues
    resources :regim_especials
    resources :regim_propietats
    resources :declaracions
    resources :llicencies
    resources :garantia_instalacions
    resources :garantia_promotors
    resources :coordinadors
    resources :colaboradors
    resources :garantia_constructors
    resources :energia_certificats
    resources :referencia_calendaris
    resources :aptitud_certificats
    resources :iites
    resources :info_usuaris
    resources :pagaments
    resources :empresa_factures
    resources :usuari_factures
    resources :signatura_llibres
    resources :signatura_instruccions
    resources :signatura_promotors
    resources :inscripcio_registrals
  end
  
  
  devise_for :users
  
  
  get 'pagaments/llistat_pagaments'
  get 'pagaments/detall_pagament'
  get 'pagaments/cambra_projects'
  
  
  
  
  get 'home/index'
  get 'home/tutorial'
  get 'home/permisos'
  get 'home/contacta'
  get 'home/avis'
  root :to => "home#index"
  
  match ':controller(/:action(/:id))', :via => [:get, :post]
  

end

app/models/especial.rb
class Especial < ActiveRecord::Base

	belongs_to :edifici

end

app/controllers/especials_controller.rb
class EspecialsController < ApplicationController
  include CheckUser
  include SetSistemes
  before_action :set_sistemes, only: [:show, :edit, :update, :destroy]
  layout 'edifici'

  # GET /especials
  # GET /especials.json
  def index
    @especials = Especial.all
  end

  # GET /especials/1
  # GET /especials/1.json
  def show
  end

  # GET /especials/new
  def new
    @especial = Especial.new
  end

  # GET /especials/1/edit
  def edit
    # Comprovació edifici pertany a usuari
    check_user_edifici
    # Comprovació pàgina correspon a edifici
    if @edifici.especial.id != params[:id].to_i
      redirect_to home_permisos_path
    end

    @submenu_actiu = 'sistemes'
    @menu_sistemes_actiu = 'especials'
    @elements = Element.where(:edifici_id => @edifici.id, :sistema_element => 'especials')
  end

  # POST /especials
  # POST /especials.json
  def create
    @especial = Especial.new(especial_params)

    respond_to do |format|
      if @especial.save
        format.html { redirect_to @especial, notice: 'Especial was successfully created.' }
        format.json { render :show, status: :created, location: @especial }
      else
        format.html { render :new }
        format.json { render json: @especial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /especials/1
  # PATCH/PUT /especials/1.json
  def update
    respond_to do |format|
      if @especial.update(especial_params)
        format.html { redirect_to edit_edifici_especial_path, notice: t('.guardat_ok') }
        format.json { render :show, status: :ok, location: @especial }
      else
        format.html { render :edit }
        format.json { render json: @especial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /especials/1
  # DELETE /especials/1.json
  def destroy
    @especial.destroy
    respond_to do |format|
      format.html { redirect_to especials_url, notice: 'Especial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_especial
      @especial = Especial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def especial_params
      params.require(:especial).permit(:edifici_id, :piscina_estructura_obra, :piscina_estructura_composite, :piscina_estructura_acer, :piscina_vores_formigo, :piscina_vores_pedra, :piscina_ceramica, :piscina_resines, :piscina_porcellana, :piscina_climatitzacio, :piscina_iluminacio, :piscina_purificador)
    end
end

app/helpers/especials_helper.rb
module EspecialsHelper
end

app/views/especials/_form.html.erb
<%= simple_form_for([@edifici, @especial]) do |f| %>
  <%= f.error_notification %>
  
  <div class="form-inputs">
    <%= f.input :edifici_id, :as => :hidden, :input_html => { :value => @edifici.id } %>
    <div class="row">
      <div class="medium-12 columns">
        <div class="titol-sistema"><%= t('.titol_especials') %></div>
      </div>
    </div>

    <% flash.each do |key, value| %>
      <div class="row">
        <div class="large-6 columns end">
          <div data-alert class="alert-box success radius">
            <%= value %>
            <a href="#" class="close">&times;</a>
          </div>
        </div>
      </div>
    <% end %>

    <div class="row">
      <div class="medium-12 columns">
        <div class="titol-subsistema"><%= t('.piscina') %></div>
        <div class="row">
          <div class="medium-6 columns">
            <%= f.input :piscina_estructura_obra %>
            <%= f.input :piscina_estructura_composite %>
            <%= f.input :piscina_estructura_acer %>
            <%= f.input :piscina_vores_formigo %>
            <%= f.input :piscina_vores_pedra %>
            <%= f.input :piscina_ceramica %>
            <%= f.input :piscina_resines %>
            <%= f.input :piscina_porcellana %>
          </div>
          <div class="medium-6 columns">
            <%= f.input :piscina_climatitzacio %>
            <%= f.input :piscina_iluminacio %>
            <%= f.input :piscina_purificador %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="medium-12 columns">
      <div class="form-actions">
        <%= f.button :submit, t('.guardar'), :class => 'button small radius right botodreta' %>
      </div>
    </div>
  </div>
<% end %>

app/views/especials/edit.html.erb
<div id="modal-elements" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
  <h3 id="modalTitle"><%= t('.nou_element') %></h3>
  <div id="formulari-element" class="formulari-element">
  </div>
  <a class="close-reveal-modal" aria-label="Close">&#215;</a>
</div>

<div class="background-seccio">
	<div class="row">
		<div class="large-12 columns">
			<div class="titol-seccio">
				<%= t('.titol_sistemes') %>
			</div>
		</div>
	</div>
	
	<div class="row">
		<div class="medium-3 columns">
			<%= render 'layouts/menu_sistemes' %>
		</div>
		<div class="medium-9 columns">
			<div class="formulari-sistema">
				<%= render 'form' %>
				<div class="titol-subsistema"><%= t('.altres_elements') %></div>
				
				<div id="elements">
					<%= render  :partial => '/elements/llistat_elements' %>
				</div>
				<div class="row">
					<div class="medium-12 columns">
						<div class="elements-usuari">
							<%= link_to (new_edifici_element_path(:sistema => 'especials')), remote: true do %>
								<div class="afegir-element right"><span class="suma">+</span> <%= t('.afegir_element') %></div>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/especials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Especials</h1>

<table>
  <thead>
    <tr>
      <th>Edifici</th>
      <th>Piscina estructura obra</th>
      <th>Piscina estructura composite</th>
      <th>Piscina estructura acer</th>
      <th>Piscina vores formigo</th>
      <th>Piscina vores pedra</th>
      <th>Piscina ceramica</th>
      <th>Piscina porcellana</th>
      <th>Piscina climatitzacio</th>
      <th>Piscina iluminacio</th>
      <th>Piscina purificador</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @especials.each do |especial| %>
      <tr>
        <td><%= especial.edifici_id %></td>
        <td><%= especial.piscina_estructura_obra %></td>
        <td><%= especial.piscina_estructura_composite %></td>
        <td><%= especial.piscina_estructura_acer %></td>
        <td><%= especial.piscina_vores_formigo %></td>
        <td><%= especial.piscina_vores_pedra %></td>
        <td><%= especial.piscina_ceramica %></td>
        <td><%= especial.piscina_porcellana %></td>
        <td><%= especial.piscina_climatitzacio %></td>
        <td><%= especial.piscina_iluminacio %></td>
        <td><%= especial.piscina_purificador %></td>
        <td><%= link_to 'Show', especial %></td>
        <td><%= link_to 'Edit', edit_especial_path(especial) %></td>
        <td><%= link_to 'Destroy', especial, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Especial', new_especial_path %>

app/views/especials/new.html.erb
<h1>New Especial</h1>

<%= render 'form' %>

<%= link_to 'Back', especials_path %>

app/views/especials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Edifici:</strong>
  <%= @especial.edifici_id %>
</p>

<p>
  <strong>Piscina estructura obra:</strong>
  <%= @especial.piscina_estructura_obra %>
</p>

<p>
  <strong>Piscina estructura composite:</strong>
  <%= @especial.piscina_estructura_composite %>
</p>

<p>
  <strong>Piscina estructura acer:</strong>
  <%= @especial.piscina_estructura_acer %>
</p>

<p>
  <strong>Piscina vores formigo:</strong>
  <%= @especial.piscina_vores_formigo %>
</p>

<p>
  <strong>Piscina vores pedra:</strong>
  <%= @especial.piscina_vores_pedra %>
</p>

<p>
  <strong>Piscina ceramica:</strong>
  <%= @especial.piscina_ceramica %>
</p>

<p>
  <strong>Piscina porcellana:</strong>
  <%= @especial.piscina_porcellana %>
</p>

<p>
  <strong>Piscina climatitzacio:</strong>
  <%= @especial.piscina_climatitzacio %>
</p>

<p>
  <strong>Piscina iluminacio:</strong>
  <%= @especial.piscina_iluminacio %>
</p>

<p>
  <strong>Piscina purificador:</strong>
  <%= @especial.piscina_purificador %>
</p>

<%= link_to 'Edit', edit_especial_path(@especial) %> |
<%= link_to 'Back', especials_path %>